### ISSUE TITLE
Downloading Resources Error

### ISSUE THREAD

**Issue by SacredGhost** [Vergepoland/r6-downloader#1]
It is stuck trying to download 7zip but it can't find the archive

![image](https://github.com/user-attachments/assets/62eb8e0b-4fb5-463d-9dea-17d30d6698a4)

**Comment by SacredGhost** [comment]
This seems to be a common theme, even after manually added all of the resources and commenting out the resource download, 
"Resources\cmdMenuSel" is not recognized like it doesn't exist.

**Comment by SacredGhost** [comment]
I can confirm that this is all related to incorrect file paths. I don't know if this is a me issue or a Windows 11 issue, but I have found that both of these problems are fixed when the file path is forced 
![image](https://github.com/user-attachments/assets/7c4f7874-e488-4134-91b8-48565cd60abc)

**Comment by SacredGhost** [comment]
I have figured out my problem. This is my own problem that I did to myself, but long story short, I had all of my stuff in my R6Downloader folder launch as administrator automatically on my own doing from a different unrelated issue, and this was causing the file paths to be incorrect from how admin mode works with cmd.

**Comment by Vergepoland** [comment]
Hi there,
It's a "known issue," and the issue is that you ran it as admin.
I think that the "cannot find archive" error comes from the fact that 7-zip doesn't have admin rights to extract the depotdownloader framework zip file = can't view it.
Also, the downloader is set so that it will create the resources folder in the directory where the downloader is located in. So if you were to run the downloader as admin, the needed tools will be downloaded in c:/Windows/Program Files (x86?), and it'll just break from there.

This explanation probably is bad, but simple answer: you ran it as admin, won't work

**Comment by Vergepoland** [comment]
> I can confirm that this is all related to incorrect file paths. I don't know if this is a me issue or a Windows 11 issue, but I have found that both of these problems are fixed when the file path is forced 
> ![image](https://github.com/user-attachments/assets/7c4f7874-e488-4134-91b8-48565cd60abc)
> 
 

Will work, but only for you. It'll immediately break when you move the downloader to a different directory
